# Generated by Django 6.0.1 on 2026-03-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userquery'),
    ]

    operations = [
    ]
