# Generated by Django 6.0.1 on 2026-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20260312_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='language',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
