# Generated by Django 6.0.1 on 2026-03-12 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_userquery_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['keyword'], name='main_app_us_keyword_eaf705_idx'),
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['category'], name='main_app_us_categor_d6e6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['created_at'], name='main_app_us_created_4697dc_idx'),
        ),
    ]
