# Generated by Django 6.0.3 on 2026-03-16 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_userquery_keyword_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('fees', 'Fees'), ('admission', 'Admission'), ('campus', 'Campus Life'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['language'], name='main_app_us_languag_22e400_idx'),
        ),
    ]
