# Generated by Django 6.0.3 on 2026-03-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_userquery_category_alter_userquery_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('fees', 'Fees'), ('admission', 'Admission'), ('campus', 'Campus Life'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
